import { BedDouble, Building2, Loader2, MapPinned, Pencil, Plus, RefreshCw, X } from 'lucide-react'
import { useCallback, useEffect, useMemo, useState, type FormEvent } from 'react'
import { useAuth } from '../../../contexts/AuthContext'
import { adminCommercialCatalogClient, type PublicCommercialItem } from '../../../services/commercial.service'
import { ControlStorageUpload } from '../../components/control/ControlStorageUpload'
import { CrystalSelect } from '../../components/shared/CrystalSelect'
import { SectionTitle } from '../../components/shared/SectionTitle'
import { StatusBadge } from '../../components/shared/StatusBadge'
import { money } from './controlCopy'

type CatalogEntity = 'cabins' | 'restaurants' | 'venues'
type FormState = {
  id: string; slug: string; name: string; subtitle: string; description: string; price: string; priceUnit: string;
  minGuests: string; maxGuests: string; nights: string; inclusions: string; alias: string; fullAddress: string;
  city: string; state: string; phone: string; hours: string; reservationTimes: string; reservationEnabled: string; capacity: string;
  dimensions: string; status: string; visibleInApp: string; verificationStatus: string; coverImageUrl: string; sortOrder: string;
  metadata: Record<string, unknown>;
}

const emptyForm: FormState = { id: '', slug: '', name: '', subtitle: '', description: '', price: '0', priceUnit: 'pareja', minGuests: '2', maxGuests: '2', nights: '1', inclusions: '', alias: '', fullAddress: '', city: '', state: '', phone: '', hours: '', reservationTimes: '', reservationEnabled: 'true', capacity: '1', dimensions: '', status: 'draft', visibleInApp: 'false', verificationStatus: 'verified', coverImageUrl: '', sortOrder: '0', metadata: {} }
const config: Record<CatalogEntity, { label: string; singular: string; icon: typeof BedDouble; bucket: string }> = { cabins: { label: 'Paquetes de cabaña', singular: 'paquete', icon: BedDouble, bucket: 'cabins' }, restaurants: { label: 'Restaurantes', singular: 'restaurante', icon: Building2, bucket: 'restaurants' }, venues: { label: 'Espacios para eventos', singular: 'espacio', icon: MapPinned, bucket: 'venues' } }

function canWrite(roles: string[]) { return roles.some((role) => ['super_admin', 'admin', 'operations', 'marketing'].includes(role)) }
function reservationTimesFromMetadata(metadata: Record<string, unknown> | undefined) {
  return Array.isArray(metadata?.reservationTimes)
    ? metadata.reservationTimes.filter((value): value is string => typeof value === 'string').join('\n')
    : ''
}
function formFromItem(item: PublicCommercialItem): FormState { return { ...emptyForm, id: item.id, slug: item.slug, name: item.name, subtitle: item.subtitle ?? '', description: item.description ?? '', price: String(item.price ?? 0), priceUnit: item.priceUnit ?? 'pareja', minGuests: String(item.minGuests ?? 2), maxGuests: String(item.maxGuests ?? 2), nights: String(item.nights ?? 1), inclusions: item.inclusions?.join('\n') ?? '', alias: item.alias ?? '', fullAddress: item.address ?? '', city: String((item as { city?: string }).city ?? ''), state: String((item as { state?: string }).state ?? ''), phone: String((item as { phone?: string }).phone ?? ''), hours: Object.values(item.hours ?? {}).map(String).join(' · '), reservationTimes: reservationTimesFromMetadata(item.metadata), reservationEnabled: String(item.reservationEnabled ?? true), capacity: String(item.capacity ?? 1), dimensions: item.dimensions ?? '', status: item.status ?? 'draft', visibleInApp: String(item.visibleInApp ?? false), verificationStatus: item.verificationStatus ?? 'verified', coverImageUrl: item.coverImageUrl ?? '', sortOrder: String(item.sortOrder ?? 0), metadata: item.metadata ?? {} } }

export function CommercialCatalogPage() {
  const { session, roles } = useAuth()
  const token = session?.access_token
  const writable = canWrite(roles)
  const [entity, setEntity] = useState<CatalogEntity>('cabins')
  const [data, setData] = useState<Record<CatalogEntity, PublicCommercialItem[]>>({ cabins: [], restaurants: [], venues: [] })
  const [loading, setLoading] = useState(true)
  const [saving, setSaving] = useState(false)
  const [error, setError] = useState('')
  const [toast, setToast] = useState('')
  const [formOpen, setFormOpen] = useState(false)
  const [form, setForm] = useState<FormState>(emptyForm)

  const load = useCallback(async () => { setLoading(true); setError(''); try { const response = await adminCommercialCatalogClient.list(token); setData({ cabins: response.data.cabins, restaurants: response.data.restaurants, venues: response.data.venueSpaces }) } catch (loadError) { setError(loadError instanceof Error ? loadError.message : 'No fue posible cargar servicios.') } finally { setLoading(false) } }, [token])
  useEffect(() => { void load() }, [load])
  const current = data[entity]
  const published = useMemo(() => current.filter((item) => item.status === 'published' && item.visibleInApp).length, [current])

  function openCreate() { setForm({ ...emptyForm }); setFormOpen(true) }
  function openEdit(item: PublicCommercialItem) { setForm(formFromItem(item)); setFormOpen(true) }

  async function submit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault(); setSaving(true); setError('')
    const reservationTimes = [...new Set(form.reservationTimes.split(/\s+/).map((value) => value.trim()).filter((value) => /^(?:[01]\d|2[0-3]):[0-5]\d$/.test(value)))].sort()
    const common = { slug: form.slug, name: form.name, status: form.status, visibleInApp: form.visibleInApp === 'true', verificationStatus: form.verificationStatus, coverImageUrl: form.coverImageUrl || null, sortOrder: Number(form.sortOrder), metadata: { ...form.metadata, managedBy: 'control_center' } }
    const payload = entity === 'cabins'
      ? { ...common, subtitle: form.subtitle || null, description: form.description || null, price: Number(form.price), currency: 'MXN', priceUnit: form.priceUnit, minGuests: Number(form.minGuests), maxGuests: Number(form.maxGuests), nights: Number(form.nights), inclusions: form.inclusions.split('\n').map((value) => value.trim()).filter(Boolean) }
      : entity === 'restaurants'
        ? { ...common, metadata: { ...common.metadata, reservationTimes }, alias: form.alias || null, description: form.description || null, fullAddress: form.fullAddress || null, city: form.city || null, state: form.state || null, phone: form.phone || null, hours: form.hours ? { general: form.hours } : {}, reservationEnabled: form.reservationEnabled === 'true' }
        : { ...common, capacity: Number(form.capacity), dimensions: form.dimensions, description: form.description }
    try { if (form.id) await adminCommercialCatalogClient.update(token, entity, form.id, payload); else await adminCommercialCatalogClient.create(token, entity, payload); setFormOpen(false); setToast(`${config[entity].singular[0].toUpperCase()}${config[entity].singular.slice(1)} guardado.`); await load() }
    catch (submitError) { setError(submitError instanceof Error ? submitError.message : 'No fue posible guardar el servicio.') }
    finally { setSaving(false) }
  }

  return <div className="control-page control-page--catalog min-w-0 space-y-6">
    <div className="flex flex-col gap-4 xl:flex-row xl:items-end xl:justify-between"><SectionTitle eyebrow="Catálogo de servicios" title="Servicios, sedes y hospedaje" subtitle="Administra lo que Hacienda vende y opera, con imagen, publicación y visibilidad en app." /><div className="control-action-bar xl:justify-end"><button type="button" onClick={load} className={secondary}><RefreshCw size={15} />Actualizar</button><button type="button" disabled={!writable} onClick={openCreate} className={primary}><Plus size={15} />Nuevo {config[entity].singular}</button></div></div>
    <section className="grid gap-3 md:grid-cols-3">{(Object.keys(config) as CatalogEntity[]).map((key) => { const Icon = config[key].icon; return <button type="button" key={key} onClick={() => setEntity(key)} className={`flex items-center justify-between rounded-xl border p-4 text-left shadow-[var(--shadow-card)] ${entity === key ? 'border-[var(--color-burgundy)] bg-[var(--color-soft)]' : 'border-[var(--color-line)] bg-[var(--color-panel)]'}`}><div><p className="text-sm font-semibold">{config[key].label}</p><p className="mt-1 text-xs text-[var(--color-muted)]">{data[key].length} registros</p></div><Icon size={20} className="text-[var(--color-burgundy)]" /></button> })}</section>
    <section className="flex flex-wrap gap-3 rounded-xl border border-[var(--color-line)] bg-[var(--color-panel)] p-4 text-xs shadow-[var(--shadow-card)]"><span><strong>{current.length}</strong> registros</span><span><strong>{published}</strong> publicados y visibles</span><span><strong>{current.length - published}</strong> internos/borrador</span></section>
    {error ? <p className="rounded-xl border border-[#ead8c5] bg-[#fff7ed] p-4 text-sm text-[#8a4b16]">{error}</p> : null}
    {loading ? <div className="p-12"><Loader2 className="mx-auto animate-spin" /></div> : current.length === 0 ? <div className="rounded-xl border border-[var(--color-line)] bg-[var(--color-panel)] p-12 text-center text-sm text-[var(--color-muted)]">No hay {config[entity].label.toLowerCase()}. Crea el primer registro operativo.</div> : <section className="grid gap-4 md:grid-cols-2 2xl:grid-cols-3">{current.map((item) => <article key={item.id} className="overflow-hidden rounded-xl border border-[var(--color-line)] bg-[var(--color-panel)] shadow-[var(--shadow-card)]">{item.coverImageUrl ? <img src={item.coverImageUrl} alt="" className="h-36 w-full object-cover" /> : <div className="flex h-36 items-center justify-center bg-[var(--color-soft)]"><ConfigIcon entity={entity} /></div>}<div className="p-4"><div className="flex items-start justify-between gap-3"><div className="min-w-0"><p className="break-words text-sm font-semibold">{item.name}</p><p className="mt-1 break-all text-xs text-[var(--color-muted)]">/{item.slug}</p></div><StatusBadge label={item.status === 'published' && item.visibleInApp ? 'Visible en app' : item.status ?? 'Borrador'} /></div><p className="mt-3 line-clamp-2 text-xs text-[var(--color-muted-strong)]">{item.description || item.subtitle || 'Sin descripción'}</p><div className="mt-3 flex flex-wrap items-center justify-between gap-2 text-xs">{entity === 'cabins' ? <span>{money(item.price)} · {item.nights} noche(s)</span> : entity === 'venues' ? <span>{item.capacity} personas · {item.dimensions}</span> : <span>{item.reservationEnabled ? 'Acepta reservación' : 'Sin reservación'}</span>}<button type="button" disabled={!writable} onClick={() => openEdit(item)} className="inline-flex items-center justify-center gap-1 rounded-md border border-[var(--color-line)] px-2 py-1 font-semibold text-[var(--color-burgundy)] disabled:opacity-45"><Pencil size={12} />Editar</button></div></div></article>)}</section>}
    {formOpen ? <div className="control-form-overlay fixed inset-0 z-[150] flex items-center justify-center bg-[#210711]/68 p-4 backdrop-blur-sm"><button type="button" aria-label="Cerrar" className="absolute inset-0" onClick={() => setFormOpen(false)} /><form onSubmit={submit} className="control-form-surface relative z-10 max-h-[92vh] w-full max-w-5xl overflow-y-auto rounded-2xl border border-[var(--color-line)] bg-[var(--color-page)] p-6 shadow-2xl" role="dialog" aria-modal="true" aria-label={`${form.id ? 'Editar' : 'Crear'} ${config[entity].singular}`}><header className="control-form-header mb-5 flex items-center justify-between"><div><p className="text-[10px] font-semibold uppercase text-[var(--color-gold)]">{config[entity].label}</p><h2 className="mt-1 text-xl font-semibold text-[var(--color-burgundy)]">{form.id ? 'Editar' : 'Crear'} {config[entity].singular}</h2></div><button type="button" onClick={() => setFormOpen(false)} aria-label="Cerrar"><X size={17} /></button></header><div className="grid gap-4 md:grid-cols-2"><Field label="Nombre" value={form.name} onChange={(name) => setForm({ ...form, name })} required /><Field label="Enlace corto" value={form.slug} onChange={(slug) => setForm({ ...form, slug })} required />
      {entity === 'cabins' ? <><Field label="Subtítulo" value={form.subtitle} onChange={(subtitle) => setForm({ ...form, subtitle })} /><Field label="Precio" type="number" value={form.price} onChange={(price) => setForm({ ...form, price })} required /><Field label="Unidad de precio" value={form.priceUnit} onChange={(priceUnit) => setForm({ ...form, priceUnit })} required /><Field label="Mínimo huéspedes" type="number" value={form.minGuests} onChange={(minGuests) => setForm({ ...form, minGuests })} required /><Field label="Máximo huéspedes" type="number" value={form.maxGuests} onChange={(maxGuests) => setForm({ ...form, maxGuests })} required /><Field label="Noches" type="number" value={form.nights} onChange={(nights) => setForm({ ...form, nights })} required /><TextArea label="Incluye (un concepto por línea)" value={form.inclusions} onChange={(inclusions) => setForm({ ...form, inclusions })} /></> : null}
      {entity === 'restaurants' ? <><Field label="Alias" value={form.alias} onChange={(alias) => setForm({ ...form, alias })} /><Field label="Teléfono" value={form.phone} onChange={(phone) => setForm({ ...form, phone })} /><Field label="Dirección" value={form.fullAddress} onChange={(fullAddress) => setForm({ ...form, fullAddress })} wide /><Field label="Ciudad" value={form.city} onChange={(city) => setForm({ ...form, city })} /><Field label="Estado" value={form.state} onChange={(state) => setForm({ ...form, state })} /><Field label="Horario público" value={form.hours} onChange={(hours) => setForm({ ...form, hours })} wide /><TextArea label="Horarios de solicitud (uno por línea, HH:mm)" value={form.reservationTimes} onChange={(reservationTimes) => setForm({ ...form, reservationTimes })} /><label><span className={labelClass}>Reservaciones</span><CrystalSelect value={form.reservationEnabled} onChange={(reservationEnabled) => setForm({ ...form, reservationEnabled })}><option value="true">Habilitadas</option><option value="false">Deshabilitadas</option></CrystalSelect></label></> : null}
      {entity === 'venues' ? <><Field label="Capacidad" type="number" value={form.capacity} onChange={(capacity) => setForm({ ...form, capacity })} required /><Field label="Dimensiones" value={form.dimensions} onChange={(dimensions) => setForm({ ...form, dimensions })} required /></> : null}
      <TextArea label="Descripción" value={form.description} onChange={(description) => setForm({ ...form, description })} required={entity === 'venues'} /><label><span className={labelClass}>Estado editorial</span><CrystalSelect value={form.status} onChange={(status) => setForm({ ...form, status })}><option value="draft">Borrador</option><option value="published">Publicado</option><option value="inactive">Inactivo</option><option value="archived">Archivado</option></CrystalSelect></label><label><span className={labelClass}>Visible en app</span><CrystalSelect value={form.visibleInApp} onChange={(visibleInApp) => setForm({ ...form, visibleInApp })}><option value="false">No</option><option value="true">Sí</option></CrystalSelect></label><label><span className={labelClass}>Verificación</span><CrystalSelect value={form.verificationStatus} onChange={(verificationStatus) => setForm({ ...form, verificationStatus })}><option value="verified">Verificado</option><option value="pending_client_confirmation">Pendiente de confirmar</option></CrystalSelect></label><Field label="Orden de aparición" type="number" value={form.sortOrder} onChange={(sortOrder) => setForm({ ...form, sortOrder })} /><div className="md:col-span-2"><span className={labelClass}>Imagen principal</span><ControlStorageUpload bucket={config[entity].bucket} pathPrefix={`${entity}/${form.id || form.slug || 'draft'}`} value={form.coverImageUrl} onChange={(coverImageUrl) => setForm({ ...form, coverImageUrl })} label="imagen" accept="image/jpeg,image/png,image/webp,image/avif" publicFile image /></div><div className="control-form-actions md:col-span-2"><button type="button" onClick={() => setFormOpen(false)} className={secondary}>Cancelar</button><button type="submit" disabled={saving} className={primary}>{saving ? <Loader2 size={14} className="animate-spin" /> : <Plus size={14} />}{form.id ? 'Guardar cambios' : 'Crear registro'}</button></div></div></form></div> : null}
    {toast ? <div className="fixed bottom-6 right-6 z-[180] rounded-xl border border-[rgba(37,47,55,0.24)] bg-white px-4 py-3 text-sm font-semibold text-[#252F37] shadow-xl">{toast}<button onClick={() => setToast('')} className="ml-3"><X size={14} /></button></div> : null}
  </div>
}

function ConfigIcon({ entity }: { entity: CatalogEntity }) { const Icon = config[entity].icon; return <Icon size={30} className="text-[var(--color-burgundy)]" /> }
const secondary = 'inline-flex min-h-10 items-center gap-2 rounded-xl border border-[var(--color-line)] bg-white px-4 text-xs font-semibold text-[var(--color-burgundy)] disabled:opacity-45'
const primary = 'inline-flex min-h-10 items-center gap-2 rounded-xl bg-[var(--color-burgundy)] px-4 text-xs font-semibold text-white disabled:opacity-45'
const labelClass = 'mb-1 block text-[10px] font-semibold uppercase text-[var(--color-muted)]'
function Field({ label, value, onChange, type = 'text', required, wide }: { label: string; value: string; onChange: (value: string) => void; type?: string; required?: boolean; wide?: boolean }) { return <label className={wide ? 'md:col-span-2' : ''}><span className={labelClass}>{label}{required ? ' *' : ''}</span><input type={type} step={type === 'number' ? 'any' : undefined} min={type === 'number' ? '0' : undefined} required={required} value={value} onChange={(event) => onChange(event.target.value)} className="min-h-11 w-full rounded-xl border border-[var(--color-line)] bg-white px-3 text-sm outline-none" /></label> }
function TextArea({ label, value, onChange, required }: { label: string; value: string; onChange: (value: string) => void; required?: boolean }) { return <label className="md:col-span-2"><span className={labelClass}>{label}{required ? ' *' : ''}</span><textarea rows={3} required={required} value={value} onChange={(event) => onChange(event.target.value)} className="w-full rounded-xl border border-[var(--color-line)] bg-white px-3 py-3 text-sm outline-none" /></label> }
